### ISSUE TITLE
Bizarre Interior Lighting Glitch

### ISSUE THREAD

**Issue by J-McFc** [zesterer/openmw-volumetric-clouds#11] opened 2022-09-24 09:51 UTC
I've come across these bizarre lighting glitches while indoor, it seems as though the candles are floating around in the air. I can't really describe it, so check out this vid: https://youtu.be/EW6opSzxzWI

I've tested this on the 0.48 RC as well as the latest 0.49 developmental build. 

Does anyone have a clue what's causing this?

**Comment by zesterer** [comment] 2022-09-25 09:45
This isn't an issue with this volumetric cloud mod, but is a duplicate of https://github.com/zesterer/openmw-shaders/issues/9 in my shader mod. Solutions are available on that issue :)

**Closed by zesterer** 2022-09-25 09:45 UTC

**Comment by J-McFc** [comment] 2022-09-25 09:47
Oh damn haha yeah wrong mod, thanks for the link.
